name: Reusable - deploy
on:
    workflow_call:
        inputs:
            sha:
                required: true
                type: string
        # secrets:#
        #     AWS_ROLE_TO_ASSUME:
        #         required: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: docker-complex
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4

            - name: Configure AWS credentials (OIDC)
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
                  aws-region: eu-north-1

            - name: Inject image tag
              env:
                  IMAGE_TAG: ${{ github.sha }}
              run: |
                  sed -i "s/__IMAGE_TAG__/${IMAGE_TAG}/g" docker-compose.yml

            - name: Create deploy bundle (docker-compose)
              run: zip -r deploy.zip docker-compose.yml

            - name: Deploy to Elastic Beanstalk
              uses: aws-actions/aws-elasticbeanstalk-deploy@v1.0.0
              with:
                  application-name: complex
                  environment-name: Complex-env-1
                  version-label: docker-${{ github.sha }}-${{ github.run_number }}
                  deployment-package-path: deploy.zip
                  aws-region: eu-north-1
                  create-environment-if-not-exists: false
                  create-application-if-not-exists: false
