name: Deploy k8s
on:
    workflow_dispatch:
    push:
        branches: [main]
        paths-ignore:
            - "**.md"
            - "screenshots/**"
            - "commands.sh"
            - "commands_github_cli.sh"
            - ".gitignore"
    pull_request:
        branches: [main]
        paths-ignore:
            - "**.md"
            - "screenshots/**"
            - "commands.sh"
            - "commands_github_cli.sh"
            - ".gitignore"


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: k8s
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # ---------- push only ----------
      - name: Authenticate to Google Cloud
        if: github.event_name == 'push'
        uses: google-github-actions/auth@v3
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # ---------- push only ----------
      - name: Set up gcloud
        if: github.event_name == 'push'
        uses: google-github-actions/setup-gcloud@v2

      # ---------- push only ----------  
      - name: Get GKE credentials
        if: github.event_name == 'push'
        uses: google-github-actions/get-gke-credentials@v3
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_LOCATION }}

      # ---------- push only ----------
      - name: Login to Docker Hub
        if: github.event_name == 'push'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test image
        run: |
          docker buildx build \
            --cache-from type=gha,scope=react-test \
            --cache-to type=gha,mode=max,scope=react-test \
            --load \
            -t milosfaktor/react-test \
            -f ./client/Dockerfile.dev \
            ./client

      - name: Run tests
        run: docker run -e CI=true milosfaktor/react-test npm test

      # ---------- push only ----------
      - name: Build images from script
        if: github.event_name == 'push'
        run: ./scripts/build.sh

      # ---------- push only ----------
      - name: Deploy images from script
        if: github.event_name == 'push'
        run: ./scripts/deploy.sh
      

      # ========= workflow without scripts and cache ===========
      
      # - name: Build production images
      #   run: |
      #     docker build -t milosfaktor/multi-client:${{ github.sha }} -t milosfaktor/multi-client:latest ./client
      #     docker build -t milosfaktor/maulti-server:${{ github.sha }} -t milosfaktor/multi-server:latest ./server
      #     docker build -t milosfaktor/multi-worker:${{ github.sha }} -t milosfaktor/multi-worker:latest ./worker

      # - name: Push images
      #   run: |
      #     docker push milosfaktor/multi-client:${{ github.sha }}
      #       docker push milosfaktor/multi-client:latest
      #       docker push milosfaktor/multi-server:${{ github.sha }}
      #       docker push milosfaktor/multi-server:latest
      #       docker push milosfaktor/multi-worker:${{ github.sha }}
      #       docker push milosfaktor/multi-worker:latest

      # - name: Apply Kubernetes configs
      #   run: kubectl apply -f k8s

      # - name: Update deployment images
      #   run: |
      #     kubectl set image deployments/server-deployment server=milosfaktor/multi-server:${{ github.sha }}
      #     kubectl set image deployments/client-deployment client=milosfaktor/multi-client:${{ github.sha }}
      #     kubectl set image deployments/worker-deployment worker=milosfaktor/multi-worker:${{ github.sha }}

      # - name: Wait for rollouts
      #   run: |
      #     kubectl rollout status deployment/client-deployment
      #     kubectl rollout status deployment/server-deployment
      #     kubectl rollout status deployment/worker-deployment